#!/bin/bash

    --scale-tier STANDARD_1 \

JOB_NAME=svhn_23_multiple_machines
BUCKET_NAME=mindful-experience-4425
OUTPUT_PATH=gs://$BUCKET_NAME/$JOB_NAME
DATA_PATH=gs://$BUCKET_NAME/data/SVHN.pickle

gcloud ml-engine jobs submit training $JOB_NAME \
    --job-dir $OUTPUT_PATH \
    --runtime-version 1.0 \
    --module-name SingleDigitClassification/task \
    --package-path SingleDigitClassification/ \
    --scale-tier STANDARD_1 \
    -- \
    --file-path $DATA_PATH \
    --train-steps 10000 \

python -m tensorflow.tensorboard --logdir=$OUTPUT_PATH
